language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t websstone/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true websstone/docker-react npm run test
  